version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

before_build:
  - nuget restore AcademicMarketplace.sln
  - npm install --save-dev frisby

build_script:
  - msbuild "C:\projects\academicmarketplace\AcademicMarketplace.sln" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

test_script:
  - cmd: echo About to start it
  - ps: $MyProcess = Start-Process C:\projects\academicmarketplace\AcademicMarketplace\bin\AcademicMarketplace1.dll -PassThru
  - cmd: echo Start is done
  - ps: Start-Sleep -s 10
  - cmd: echo Sleep is done
  - ps: Stop-Process -Id $MyProcess.Id
  - cmd: echo Stop is done

test:
  assemblies:
    - '**\*.UnitTesting.dll'
