version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

before_build:
  - nuget restore AcademicMarketplace.sln
  - npm install --save-dev frisby

test:
  assemblies:
    - '**\*.UnitTesting.dll'
