version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

before_build:
  - nuget restore AcademicMarketplace.sln
  - npm install --save-dev frisby

test_script:
- cmd: echo About to run
- cmd: dotnet run --project AcademicMarketplace/Application.AcademicMarketplace.csproj
- cmd: echo Run finished

test:
  assemblies:
    - '**\*.UnitTesting.dll'
