//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademicMarketplace.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        public int Id { get; set; }
        public int MarketListing { get; set; }
        public string RequestedBy { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MarketplaceListing MarketplaceListing { get; set; }
    }
}
