/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module T4TS {
    /** Generated from AcademicMarketplace.Controllers.Models.MarketplacePostingResponse **/
    export interface IMarketplacePostingResponse {
        postId: number;
        postTitle: string;
        postContent: string;
        postDate: string;
        postedBy: number;
        completedDate: string;
        completedBy: number;
        active: boolean;
    }
}
