/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module Models.BalanceModel {
    /** Generated from AcademicMarketplace.Controllers.Models.BalanceModel **/
    export interface IBalanceModel {
        user: string;
        balance?: number;
    }
}

declare module Models.MarketplaceListingModel {
    /** Generated from AcademicMarketplace.Controllers.Models.MarketplaceListingModel **/
    export interface IMarketplaceListingModel {
        id: number;
        workgroup: string;
        name: string;
        description: string;
        image: string;
        workgroup1: Models.WorkgroupModel.IWorkgroupModel;
        serviceRequests: Models.ServiceRequestModel.IServiceRequestModel[];
    }
}

declare module Models.ServiceRequestModel {
    /** Generated from AcademicMarketplace.Controllers.Models.ServiceRequestModel **/
    export interface IServiceRequestModel {
        id: number;
        marketListing: number;
        requestedBy: string;
        status: string;
        requestedBy1: Models.UserModel.IUserModel;
        marketListing1: Models.MarketplaceListingModel.IMarketplaceListingModel;
    }
}

declare module Models.UserModel {
    /** Generated from AcademicMarketplace.Controllers.Models.UserModel **/
    export interface IUserModel {
        id: string;
        username: string;
        email: string;
        firstName: string;
        surname: string;
        location: string;
        balance: Models.BalanceModel.IBalanceModel;
        serviceRequests: Models.ServiceRequestModel.IServiceRequestModel[];
        workgroups: Models.WorkgroupModel.IWorkgroupModel[];
    }
}

declare module Models.WorkgroupModel {
    /** Generated from AcademicMarketplace.Controllers.Models.WorkgroupModel **/
    export interface IWorkgroupModel {
        code: string;
        name: string;
        description: string;
        marketplaceListings: Models.MarketplaceListingModel.IMarketplaceListingModel[];
        users: Models.UserModel.IUserModel[];
    }
}
