/****************************************************************************
  Generated by T4TS.tt - don't make any changes in this file
****************************************************************************/

declare module Models.BalanceModel {
    /** Generated from AcademicMarketplace.Controllers.Models.BalanceModel **/
    export interface IBalanceModel {
        userId: number;
        creditBalance?: number;
    }
}

declare module Models.PostModel {
    /** Generated from AcademicMarketplace.Controllers.Models.PostModel **/
    export interface IPostModel {
        id?: number;
        title: string;
        description: string;
        postedDate: string;
        postedBy: number;
        completedDate?: string;
        completedBy?: number;
        active: boolean;
        completedByUser: Models.UserModel.IUserModel;
        postedByUser: Models.UserModel.IUserModel;
    }
}

declare module Models.UserModel {
    /** Generated from AcademicMarketplace.Controllers.Models.UserModel **/
    export interface IUserModel {
        id?: number;
        username: string;
        firstName: string;
        lastName: string;
        admin: boolean;
        balance: Models.BalanceModel.IBalanceModel;
        postsMade: Models.PostModel.IPostModel[];
        postsCompleted: Models.PostModel.IPostModel[];
    }
}
